"""Budgets table

Revision ID: 4fef98ebbbe8
Revises: 413af6c6f0f8
Create Date: 2026-09-06 14:34:34.128291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fef98ebbbe8'
down_revision = '413af6c6f0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_user_id'))
        batch_op.drop_index(batch_op.f('ix_budget_name'))
        batch_op.drop_index(batch_op.f('ix_budget_created_at'))

    op.drop_table('budget')
    # ### end Alembic commands ###
